2025-01-23 01:56:04,473 WARNING werkzeug MainThread :  * Debugger is active!
2025-01-23 01:56:04,480 INFO werkzeug MainThread :  * Debugger PIN: 846-340-584
2025-01-23 01:56:15,384 INFO main Thread-2 (process_request_thread) : ui
2025-01-23 01:56:15,387 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:15] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:15,451 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:15] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-01-23 01:56:15,990 INFO main Thread-4 (process_request_thread) : func_2
2025-01-23 01:56:16,012 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:16] "POST /func_2 HTTP/1.1" 200 -
2025-01-23 01:56:16,661 INFO main Thread-5 (process_request_thread) : ui
2025-01-23 01:56:16,661 INFO werkzeug Thread-5 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:16] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:17,908 INFO main Thread-6 (process_request_thread) : func_2
2025-01-23 01:56:17,912 INFO main Thread-6 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 96, in func_2
    db.Database.execute(Query.post_insert(val))
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 34, in execute
    self.cursor.execute(query, args)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'input_1' at row 1")

2025-01-23 01:56:17,912 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:17] "POST /func_2 HTTP/1.1" 200 -
2025-01-23 01:56:18,401 INFO main Thread-7 (process_request_thread) : ui
2025-01-23 01:56:18,401 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:18] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:18,704 INFO main Thread-8 (process_request_thread) : func_1
2025-01-23 01:56:18,704 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:18] "GET /func_1?idx=2 HTTP/1.1" 200 -
2025-01-23 01:56:19,139 INFO main Thread-9 (process_request_thread) : ui
2025-01-23 01:56:19,140 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:19] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:19,451 INFO main Thread-10 (process_request_thread) : func_1
2025-01-23 01:56:19,452 INFO main Thread-10 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 57, in func_1
    a['data'] = db.Database.execute(Query.get_select_one(val))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 38, in execute
    raise ValueError('Index not found')
ValueError: Index not found

2025-01-23 01:56:19,452 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:19] "GET /func_1?idx=-2147483649 HTTP/1.1" 200 -
2025-01-23 01:56:19,924 INFO main Thread-11 (process_request_thread) : ui
2025-01-23 01:56:19,925 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:19] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:20,937 INFO main Thread-12 (process_request_thread) : func_1
2025-01-23 01:56:20,943 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:20] "POST /func_1 HTTP/1.1" 200 -
2025-01-23 01:56:21,387 INFO main Thread-13 (process_request_thread) : ui
2025-01-23 01:56:21,389 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:21] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:21,908 INFO main Thread-14 (process_request_thread) : func_1
2025-01-23 01:56:21,909 INFO main Thread-14 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 73, in func_1
    db.Database.execute(Query.get_select_one(int(val['idx'])))
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 38, in execute
    raise ValueError('Index not found')
ValueError: Index not found

2025-01-23 01:56:21,910 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:21] "POST /func_1 HTTP/1.1" 200 -
2025-01-23 01:56:22,348 INFO main Thread-15 (process_request_thread) : ui
2025-01-23 01:56:22,348 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:22] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:22,662 INFO main Thread-16 (process_request_thread) : func_3
2025-01-23 01:56:22,663 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:22] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:56:23,176 INFO main Thread-17 (process_request_thread) : ui
2025-01-23 01:56:23,177 INFO werkzeug Thread-17 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:23] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:23,966 INFO main Thread-18 (process_request_thread) : func_3
2025-01-23 01:56:23,967 INFO werkzeug Thread-18 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:23] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:56:24,839 INFO main Thread-19 (process_request_thread) : ui
2025-01-23 01:56:24,841 INFO werkzeug Thread-19 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:24] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:56:25,447 INFO main Thread-20 (process_request_thread) : func_3
2025-01-23 01:56:25,448 INFO werkzeug Thread-20 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:56:25] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:57:40,096 INFO main Thread-22 (process_request_thread) : ui
2025-01-23 01:57:40,097 INFO werkzeug Thread-22 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:57:40] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:57:40,163 INFO werkzeug Thread-23 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:57:40] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-01-23 01:57:40,688 INFO main Thread-24 (process_request_thread) : func_2
2025-01-23 01:57:40,700 INFO werkzeug Thread-24 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:57:40] "POST /func_2 HTTP/1.1" 200 -
2025-01-23 01:58:47,061 INFO werkzeug MainThread :  * Detected change in 'C:\\code\\PycharmProjects\\test_script\\Selenium\\item\\pytest\\Selenium_script.py', reloading
