2025-01-23 01:51:38,815 WARNING werkzeug MainThread :  * Debugger is active!
2025-01-23 01:51:38,822 INFO werkzeug MainThread :  * Debugger PIN: 846-340-584
2025-01-23 01:52:44,747 INFO main Thread-2 (process_request_thread) : ui
2025-01-23 01:52:44,749 INFO werkzeug Thread-2 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:44] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:44,817 INFO werkzeug Thread-3 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:44] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-01-23 01:52:45,267 INFO main Thread-4 (process_request_thread) : func_2
2025-01-23 01:52:45,281 INFO werkzeug Thread-4 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:45] "POST /func_2 HTTP/1.1" 200 -
2025-01-23 01:52:45,784 INFO main Thread-5 (process_request_thread) : ui
2025-01-23 01:52:45,786 INFO werkzeug Thread-5 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:45] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:46,207 INFO main Thread-6 (process_request_thread) : func_2
2025-01-23 01:52:46,211 INFO main Thread-6 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 96, in func_2
    db.Database.execute(Query.post_insert(val))
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 34, in execute
    self.cursor.execute(query, args)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'input_1' at row 1")

2025-01-23 01:52:46,212 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:46] "POST /func_2 HTTP/1.1" 200 -
2025-01-23 01:52:46,827 INFO main Thread-7 (process_request_thread) : ui
2025-01-23 01:52:46,828 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:46] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:47,205 INFO main Thread-8 (process_request_thread) : func_1
2025-01-23 01:52:47,206 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:47] "GET /func_1?idx=2 HTTP/1.1" 200 -
2025-01-23 01:52:47,604 INFO main Thread-9 (process_request_thread) : ui
2025-01-23 01:52:47,604 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:47] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:47,916 INFO main Thread-10 (process_request_thread) : func_1
2025-01-23 01:52:47,917 INFO main Thread-10 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 57, in func_1
    a['data'] = db.Database.execute(Query.get_select_one(val))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 38, in execute
    raise ValueError('Index not found')
ValueError: Index not found

2025-01-23 01:52:47,918 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:47] "GET /func_1?idx=-2147483649 HTTP/1.1" 200 -
2025-01-23 01:52:48,313 INFO main Thread-11 (process_request_thread) : ui
2025-01-23 01:52:48,314 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:48] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:48,729 INFO main Thread-12 (process_request_thread) : func_1
2025-01-23 01:52:48,734 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:48] "POST /func_1 HTTP/1.1" 200 -
2025-01-23 01:52:49,128 INFO main Thread-13 (process_request_thread) : ui
2025-01-23 01:52:49,128 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:49] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:49,571 INFO main Thread-14 (process_request_thread) : func_1
2025-01-23 01:52:49,572 INFO main Thread-14 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 73, in func_1
    db.Database.execute(Query.get_select_one(int(val['idx'])))
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 38, in execute
    raise ValueError('Index not found')
ValueError: Index not found

2025-01-23 01:52:49,572 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:49] "POST /func_1 HTTP/1.1" 200 -
2025-01-23 01:52:49,966 INFO main Thread-15 (process_request_thread) : ui
2025-01-23 01:52:49,967 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:49] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:50,276 INFO main Thread-16 (process_request_thread) : func_3
2025-01-23 01:52:50,278 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:50] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:52:50,667 INFO main Thread-17 (process_request_thread) : ui
2025-01-23 01:52:50,668 INFO werkzeug Thread-17 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:50] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:50,976 INFO main Thread-18 (process_request_thread) : func_3
2025-01-23 01:52:50,977 INFO werkzeug Thread-18 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:50] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:52:51,376 INFO main Thread-19 (process_request_thread) : ui
2025-01-23 01:52:51,376 INFO werkzeug Thread-19 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:51] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:52:51,686 INFO main Thread-20 (process_request_thread) : func_3
2025-01-23 01:52:51,687 INFO werkzeug Thread-20 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:52:51] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:54:31,940 INFO main Thread-22 (process_request_thread) : ui
2025-01-23 01:54:31,941 INFO werkzeug Thread-22 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:31] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:32,005 INFO werkzeug Thread-23 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:32] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -
2025-01-23 01:54:32,445 INFO main Thread-24 (process_request_thread) : func_2
2025-01-23 01:54:32,459 INFO werkzeug Thread-24 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:32] "POST /func_2 HTTP/1.1" 200 -
2025-01-23 01:54:32,943 INFO main Thread-25 (process_request_thread) : ui
2025-01-23 01:54:32,944 INFO werkzeug Thread-25 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:32] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:33,380 INFO main Thread-26 (process_request_thread) : func_2
2025-01-23 01:54:33,381 INFO main Thread-26 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 96, in func_2
    db.Database.execute(Query.post_insert(val))
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 34, in execute
    self.cursor.execute(query, args)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 153, in execute
    result = self._query(query)
             ^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\cursors.py", line 322, in _query
    conn.query(q)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 558, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 822, in _read_query_result
    result.read()
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 1200, in read
    first_packet = self.connection._read_packet()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\connections.py", line 772, in _read_packet
    packet.raise_for_error()
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\protocol.py", line 221, in raise_for_error
    err.raise_mysql_exception(self._data)
  File "C:\Users\¼Û¹Î±Ô\AppData\Local\Programs\Python\Python312\Lib\site-packages\pymysql\err.py", line 143, in raise_mysql_exception
    raise errorclass(errno, errval)
pymysql.err.DataError: (1264, "Out of range value for column 'input_1' at row 1")

2025-01-23 01:54:33,382 INFO werkzeug Thread-26 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:33] "POST /func_2 HTTP/1.1" 200 -
2025-01-23 01:54:33,779 INFO main Thread-27 (process_request_thread) : ui
2025-01-23 01:54:33,779 INFO werkzeug Thread-27 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:33] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:34,081 INFO main Thread-28 (process_request_thread) : func_1
2025-01-23 01:54:34,082 INFO werkzeug Thread-28 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:34] "GET /func_1?idx=2 HTTP/1.1" 200 -
2025-01-23 01:54:34,484 INFO main Thread-29 (process_request_thread) : ui
2025-01-23 01:54:34,484 INFO werkzeug Thread-29 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:34] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:34,794 INFO main Thread-30 (process_request_thread) : func_1
2025-01-23 01:54:34,794 INFO main Thread-30 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 57, in func_1
    a['data'] = db.Database.execute(Query.get_select_one(val))
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 38, in execute
    raise ValueError('Index not found')
ValueError: Index not found

2025-01-23 01:54:34,794 INFO werkzeug Thread-30 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:34] "GET /func_1?idx=-2147483649 HTTP/1.1" 200 -
2025-01-23 01:54:35,184 INFO main Thread-31 (process_request_thread) : ui
2025-01-23 01:54:35,184 INFO werkzeug Thread-31 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:35] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:35,671 INFO main Thread-32 (process_request_thread) : func_1
2025-01-23 01:54:35,678 INFO werkzeug Thread-32 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:35] "POST /func_1 HTTP/1.1" 200 -
2025-01-23 01:54:36,076 INFO main Thread-33 (process_request_thread) : ui
2025-01-23 01:54:36,076 INFO werkzeug Thread-33 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:36] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:36,488 INFO main Thread-34 (process_request_thread) : func_1
2025-01-23 01:54:36,489 INFO main Thread-34 (process_request_thread) : Traceback (most recent call last):
  File "C:\code\PycharmProjects\song\server\main.py", line 73, in func_1
    db.Database.execute(Query.get_select_one(int(val['idx'])))
  File "C:\code\PycharmProjects\song\server\db_f\db.py", line 38, in execute
    raise ValueError('Index not found')
ValueError: Index not found

2025-01-23 01:54:36,489 INFO werkzeug Thread-34 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:36] "POST /func_1 HTTP/1.1" 200 -
2025-01-23 01:54:36,894 INFO main Thread-35 (process_request_thread) : ui
2025-01-23 01:54:36,894 INFO werkzeug Thread-35 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:36] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:37,200 INFO main Thread-36 (process_request_thread) : func_3
2025-01-23 01:54:37,201 INFO werkzeug Thread-36 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:37] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:54:37,592 INFO main Thread-37 (process_request_thread) : ui
2025-01-23 01:54:37,592 INFO werkzeug Thread-37 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:37] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:37,895 INFO main Thread-38 (process_request_thread) : func_3
2025-01-23 01:54:37,896 INFO werkzeug Thread-38 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:37] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:54:38,283 INFO main Thread-39 (process_request_thread) : ui
2025-01-23 01:54:38,283 INFO werkzeug Thread-39 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:38] "GET /ui HTTP/1.1" 200 -
2025-01-23 01:54:38,599 INFO main Thread-40 (process_request_thread) : func_3
2025-01-23 01:54:38,600 INFO werkzeug Thread-40 (process_request_thread) : 127.0.0.1 - - [23/Jan/2025 01:54:38] "POST /func_3 HTTP/1.1" 200 -
2025-01-23 01:56:03,973 INFO werkzeug MainThread :  * Detected change in 'C:\\code\\PycharmProjects\\test_script\\Selenium\\item\\pytest\\Selenium_script.py', reloading
